// <auto-generated />
namespace Domainclasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class productcategoryfiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productcategoryfiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041149544_product category files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
